services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: agentstore-keycloak
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_FEATURES=upload-scripts
    volumes:
      - ./keycloak-init:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    networks:
      - agentstore-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  agentstore-network:
    name: agentstore-network
    external: true 