services:
  postgres:
    image: postgres:14
    container_name: agentstore-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=agentstore
      - POSTGRES_MULTIPLE_DATABASES=keycloak
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    networks:
      - agentstore-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  agentstore-network:
    name: agentstore-network
    driver: bridge

volumes:
  postgres-data:
    name: agentstore-postgres-data 