services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agentstore-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/agentstore
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_FLYWAY_CLEAN_DISABLED=false
      - SPRING_FLYWAY_CLEAN_ON_VALIDATION_ERROR=true
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=agentstore
      - KEYCLOAK_RESOURCE=agentstore-app
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/agentstore
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak:8080/realms/agentstore/protocol/openid-connect/certs
    networks:
      - agentstore-network
    # Commented out the volume that's causing issues
    # volumes:
    #   - ./target/agentstore.jar:/app/agentstore.jar
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  agentstore-network:
    name: agentstore-network
    external: true 